package org.mahiti.convenemis.utils;

public class ClusterInfo {
    public static final String TRAININGLABLE = "Training";
    public static final String SAATHI = "Saathi";
    public static final String LIVE = "Live";
    public static final String USERNAME = "username";
    public static final String LOGINBUTTON = "Login";
    public static final String FORGETPASS = "forgotPass";
    public static final String signin = "Signin";
    public static final String Next = "Next";
    public static final String Previous = "Previous";
    public static final String done = "Done";
    public static final String Processing = "Processing";
    public static final String Survey = "Survey";
    public static final String caseId = "CaseId";
    public static final String submit = "Submit";
    public static final String continueLabel = "Continue";
    public static final String pauseSurvey = "PauseSurvey";
    public static final String abortSurvey = "AbortSurvey";
    public static final String activityLable = "activityLable";
    public static final String Demographics = "Survey Status";
    public static final String MINI = "MINI";
    public static final String SummaryReport = "SummaryReport";
    public static final String PatientName = "Patient";
    public static final String ANCName = "ANCName";
    public static final String SiteName = "SiteName";
    public static final String Facility_Nodal_name = "Facility_Name";
    public static final String Add_New_STR = "Add_New_STR";
    public static final String Add_New_FIF = "Add_New_FIF";
    public static final String Add_New_ANC = "Add_New_ANC";
    public static final String Add_New_MSD = "Add_New_MSD";
    public static final String Select_State = "Select_State";
    public static final String Select_District = "Select_District";
    public static final String Select_Town = "Select_Town";

    public static final String Entered = "Entered";
    public static final String Pending_to_sync = "Pending_to_sync";
    public static final String Synchronized = "Synchronized";
    public static final String Add_new_data_to_survey = "Add_new_data_to_survey";
    public static final String Sync_data = "Sync_data";
    public static final String Clear_Sync_data = "Clear_Sync_data";
    public static final String Logout = "Logout";
    public static final String HelpManual = "HelpManual";
    public static final String SwitchLanguage = "SwitchLanguage";
    public static final String SendDebugData = "SendDebugData";
    public static final String Location_Selection = "Location_Selection";
    public static final String Built_by_Mahiti = "Built_by_Mahiti";
    public static final String Select_language = "Select_language";
    public static final String Lao = "Lao";
    public static final String English = "English";
    public static final String ok = "OK";
    public static final String Data_copied_successfully = "Data_copied_successfully";
    public static final String Synchronizing_pending_data = "Synchronizing_pending_data";
    public static final String agrred = "Agreed";
    public static final String refused = "Refused";
    public static final String pleasereasonForRefused = "PleasereasonForRefused";
    public static final String reasonForRefused = "reasonForRefused";
    public static final String reasonforAbort = "reasonForAbort";
    public static final String exitFromSurvey = "exitFromSurvey";
    public static final String logOutFromSurvey = "logOutFromSurvey";
    public static final String yes = "Yes";
    public static final String no = "No";
    public static final String consentstatusMSG = "ConsentstatusMSG";
    public static final String selectClusterMSG = "selectClusterMSG";
    public static final String caseIdExistMSG = "caseIdExistMSG";
    public static final String caseIdMSG = "caseIdMSG";
    public static final String destroyCurrentRecord = "destroyCurrentRecord";
    public static final String proceed = "proceed";
    public static final String cancel = "Cancle";
    public static final String pleasewait = "pleaseWait";
    public static final String enterReason = "enterReason";
    public static final String enterAnswer = "enterAnswer";
    public static final String wouldLikeContinue = "wouldLikeContinue";
    public static final String agegreaterthan18 = "agegreaterthan18";
    public static final String noNetConn = "noNetConn";
    public static final String miniCompleted = "miniComplete";
    public static final String demographicsComplete = "demographicsComplete";
    public static final String noPendingRecToSync = "noPendingRecToSync";
    public static final String enterusername = "enterUserName";
    public static final String ENTERPASS = "enterPassword";
    public static final String USERNAMEPASS = "usernameAndpassword";
    public static final String connectionProb = "connectivityProb";
    public static final String probServerside = "probServerSide";
    public static final String plsCheckNetConn = "plsCheckNetConn";
    public static final String plsEnterSixDigit = "plsEnterSixDigits";
    public static final String loggedInOffline = "loggedInOffline";
    public static final String noSurveyDataCapture = "noSurveyDataCapture";
    public static final String plsEnterAllAnswers = "plsEnterAllAnswers";
    public static final String trainingMode = "trainingMode";
    public static final String checkNetCOnnFetchDetails = "checkNetCOnnFetchDetails";
    public static final String probConnTryLater = "probConnTryLater";
    public static final String probOccurredWhileDataSend = "probOccurredWhileDataSend";
    public static final String select = "select";
    public static final String selectOption = "selectOption";
    public static final String selectChoice = "selectChoice";
    public static final String enterValue = "enterValue";
    public static final String selectDate = "selectDate";
    public static final String selectImage = "selectImage";
    public static final String selectCamera = "selectCamera";
    public static final String selectGallery = "selectGallery";

    public static final String otherLangNotAvail = "otherLangNotAvail";
    public static final String langChanged = "langChanged";
    public static final String plsClickAgain = "plsClickAgain";
    public static final String probInstallApp = "probInstallApp";
    public static final String fetchData = "fetchData";
    public static final String emptyResponse = "emptyResponse";
    public static final String plsWaitSync = "plsWaitSync";
    public static final String someThingWrong = "someThingWrong";
    public static final String movNextSec = "movNextSec";
    public static final String rmvDataSkip = "rmvDataSkip";
    public static final String cusRegistration = "cusRegistration";
    public static final String dailyPeriodicMessage = "dailyPeriodicMessage";
    public static final String reasonForDisAgree = "reasonforDisAgree";
    public static final String noSurveyDataAvail = "noSurveyAvail";
    public static final String sixDigitCode = "sixDigitCode";
    public static final String viewLog = "viewLog"; // used in menu for multi language purpose
    public static final String testServer = "testServer"; // Test server connection by calling one feed
    public static final String connProper = "connProper"; // Test server connection by calling one feed
    public static final String connError = "connError"; // Test server connection by calling one feed
    public static final String MissingData = "Missing Data";
    public static final String RateingQuestion = "Please rate all";
    public static final String RankingQuestion = "Please rank differently";


    private ClusterInfo(){

    }
}
